from .FCN import FCN
from .UNet import UNet
from .SegNet import SegNet
from .cloudUNet import cloudUNet
from .cloudSegNet import cloudSegNet
from .self_contrast import self_contrast
from .DCNet_L1 import DCNet_L1
from .DCNet_L12 import DCNet_L12
from .DCNet_L123 import DCNet_L123